# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13f1da5b64684332b2de494df323a2e444c246f2c63a96a1de136b095048233bcfb4dd4a33e158c5625a217739be95e4d119bd19f890870c6d214a55d8e78a2b

test:
  secret_key_base: f73786843e6ca035c8aec33523a92e8a7f54ba774ed9d8c513456f512b6b3c2132b0ba59a93a6bf16c3bceac132594515e55b0a9d6f573d1fcc404abab0a8b8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
